/* DO NOT EDIT — generated by 视觉系统/generate.mjs。改值改 视觉系统/tokens.mjs，勿手改本文件。
 *
 * theme.ts — XCYJ 统一视觉系统的 Remotion 侧产物。组件【唯一】的 token 来源。
 * 组件里【不要】内联硬编码颜色/字号，一律从这里取，改一处全线变。
 *
 * ⚠️ 字体提醒：本设计系统用 4 套字族（见 fonts）。【加载】由宿主工程的 fonts.ts 负责
 *    （@remotion/fonts / 自托管 CJK）——只写名字不会自动加载。
 */

/* ───────────────────────── 颜色 ─────────────────────────
 * 语义铁律：蓝 = 命名/主体/当前对象；橙 = 品牌锚点/数值高亮。
 * 强调色（蓝/橙/peach/blue-soft）只用在【标注】上，背景/卡片/表格一律中性。
 */
export const colors = {
  // 浅色主题背景：奶油亮底【全局默认】（用作 background；纯色也可直接用作 backgroundColor）
  bgCream: '#efe7dd',
  // 奶油亮场渐变浅端（CreamDriftBackdrop 基底 linear-gradient 第二色，比 bgCream 略亮）
  bgCreamTo: '#f4ece2',
  // 漂浮奶油桃光斑（亮场缩卡 backdrop 上缓慢游走的三团云的颜色；几何/相位在组件里）
  creamClouds: ['#f3d6ba', '#efdac6', '#f1e0c8'],
  // 中性
  chrome: '#1F2428',      // 顶部细黑条 / 视频 chrome（蓝图未要求改，保留）
  ink: '#15171E',         // 浅色主题主文字（近黑）
  ink2: '#3A3A40',        // 次级文字 / 数值
  inkMuted: '#6E665C',    // 暖灰 注脚
  surface: '#EFE9E0',     // 实色卡面
  backcard: '#E5DCD0',    // 叠层卡（卡后那张）
  white: '#FFFFFF',
  // 强调（仅用于标注）
  blue: '#3D85E8',        // 命名 / 主体 / 当前对象
  blueStrong: '#2F73D6',
  blueSoft: '#DDE6F7',    // 行 / 格淡底
  orange: '#d97757',      // 品牌锚点：陶土橙（Claude 真实品牌色）
  orangeStrong: '#C25C3C',  // 陶土深色（陶土橙的深色版，同色系）
  peach: '#FAE7DC',       // 列高亮淡底
} as const;

/* ───────────────────────── 字体 ───────────────────────── */
export const fonts = {
  zh: 'Noto Sans SC',        // 中文 / 正文 / 口播标题 / 气泡（700 为主）
  display: 'Space Grotesk',  // 英文标题 / 大字 / 数值（700）
  serif: 'Source Serif 4',   // 衬线点缀 / 表头 / 模型名 / 斜体强调词（500 italic）
  mono: 'Space Mono',        // 注脚 / 指标名 / 序号 / 技术小字（400/700）
  /** @deprecated 旧组件用的西文别名，等价 display；新代码直接用 fonts.display */
  sans: 'Space Grotesk',
} as const;

/* ─────────────────────── 字号阶梯 @1080p ───────────────────────
 * 蓝图 §3.6 合并后的统一阶梯。最小可读：任何文字 ≥ minReadable(24px)。
 */
export const fontSize = {
  listFull: 96,      // 全屏大字列表 F5 — Space Grotesk 700
  titleHero: 64,     // 大字标题页主标题 F2 — Space Grotesk 700
  stat: 60,          // 数值（对比卡）— Space Grotesk 700
  cardTitle: 44,     // 玻璃卡标题 — Space Grotesk 700
  caption: 36,        // 口播标题 / 字幕级 — Noto Sans SC 700
  modelName: 34,     // 模型名（衬线）— Source Serif 4 500
  listItem: 30,      // 列表项卡 — Noto Sans SC 700
  bubble: 26,        // 气泡标签 — Noto Sans SC 700
  metaMono: 20,      // 指标注脚 / mono 标签 — Space Mono 400
  minReadable: 24,   // 手机端可读下限
} as const;

/* ───────────────────── 间距（基准 4px）───────────────────── */
export const spacing = {
  xxs: 4, xs: 8, sm: 12, md: 16, lg: 24, xl: 32, xxl: 48, xxxl: 64, section: 96,
} as const; // px

/* ───────────────────── 圆角 ─────────────────────
 * 新口播 token：video/card/listPill/ring/round。
 * 既有键名（sm/md/lg/xl/pill）保留，供现有 showcase 组件继续编译。
 */
export const radius = {
  // 新口播设计
  video: 28,         // 口播框
  card: 22,          // 实色 / 玻璃卡
  listPill: 13,      // 列表项卡
  ring: 11,          // 高亮框
  round: 999,        // 气泡
  // 兼容层（旧 showcase 组件在用，勿删）
  sm: 6, md: 8, lg: 12, xl: 16, pill: 9999,
} as const; // px

/* ───────────────────── 阴影（统一暖棕调；深玻璃卡用纯黑阴影）───────────────────── */
export const shadow = {
  video: '0 26px 56px -18px rgba(74,50,30,.46), 0 4px 12px rgba(74,50,30,.18)',
  card: '0 28px 60px -22px rgba(120,86,52,.40), 0 6px 18px -10px rgba(120,86,52,.22)',
  dark: '0 20px 50px -18px rgba(0,0,0,.50)',
  pill: '0 4px 12px rgba(20,20,25,.20)',
} as const;

/* ───────────────────── 卡片配方 ─────────────────────
 * 直接铺到 React style 上的样式对象。
 */
export const cards = {
  /** 深玉玻璃卡（浮于素材） */
  glassDark: {
    background: 'rgba(22,24,28,.66)',
    backdropFilter: 'blur(16px)',
    border: '1px solid rgba(255,255,255,.16)',
    borderRadius: radius.card,
    boxShadow: shadow.dark,
    color: '#fff',
  },
  /** 浅玉玻璃卡（浅底场景） */
  glassLight: {
    background: 'rgba(255,255,255,.74)',
    backdropFilter: 'blur(14px)',
    border: '1px solid rgba(255,255,255,.80)',
    borderRadius: radius.card,
    boxShadow: '0 20px 50px -18px rgba(74,50,30,.30)',
  },
  /** 实色卡（承载数据表） */
  cardSolid: {
    background: colors.surface,
    borderRadius: radius.card,
    boxShadow: shadow.card,
  },
  /** 列表项卡（浅底上的深色 pill） */
  listPill: {
    background: 'rgba(58,55,62,.82)',
    backdropFilter: 'blur(8px)',
    borderRadius: radius.listPill,
    color: '#fff',
  },
} as const;

/* ───────────────────── 动效 token（视频特有，帧数 @30fps）───────────────────── */
export const motion = {
  fps: 30,
  beatMinSec: 4,             // 任何静止画面 ≥4s 必须有变化
  entranceFrames: 12,        // 卡片入场典型时长 ≈0.4s
  transitionFrames: 24,      // 场景转场典型时长 ≈0.8s
  poseSlideSec: 0.8,          // 连续运镜在布局间滑动时长
  leadInFrames: 8,           // 卡片在被讲到前 ~6–10 帧入场
  beatHoldMinSec: 1.5,       // 一个信息单元至少停 1.5s 再切
  cardSpringDamping: 18,     // 卡片入场 spring({damping:18})
  cardStaggerMs: 70,          // 多卡错峰 60–80ms 逐张
  bubbleSpringDamping: 12,   // 气泡稍带回弹 spring({damping:12})
  exitFasterRatio: 0.5,      // 退场比入场快 ~1/2
  easingDefault: 'Easing.inOut(Easing.cubic)',
} as const;

/* ───────────────────── 兼容层：两套品牌 look（旧 showcase 组件契约）─────────────────────
 * GlassCards / BrandIcon / Demo / types.ts 仍用 theme.warmPaper / theme.darkGlass。
 * 键名保持不变，值换成统一视觉系统的真值。
 */
export const warmPaper = {
  canvas: '#efe7dd',         // 浅底主色（奶油亮底，全局默认）
  accent: colors.orange,     // 浅底上的陶土橙强调
  ink: colors.ink,           // 近黑主文字
  muted: colors.inkMuted,    // 暖灰注脚
  card: colors.surface,      // 实色卡面
} as const;

export const darkGlass = {
  bg: '#29201a',             // 深底回退色（espresso 暖暗底；真实场景背景是口播视频本身）
  bgGrad: 'linear-gradient(160deg,#34291f,#1d150f)',     // 全屏暖向渐变（蓝图 §3.3）——全屏镜头底色用它，禁纯黑/冷黑
  surface: 'rgba(22,24,28,.66)', // 深玉玻璃卡面（gold-standard，保留）
  stroke: 'rgba(255,255,255,.16)', // 玻璃卡描边（gold-standard，保留）
  onDark: '#F5F3EE',      // 深主题文字（暖白）
  accent: colors.blue,       // 深底上的蓝色强调（命名/主体）
  muted: 'rgba(245,243,238,.62)', // 深底上的弱化文字
  // ↓ 工程2(hyperframes-vs-remotion-intro) gold-standard 实测值（2026-06-14 token 收口）。
  //   已发布口播片是品牌样板，玻璃卡真值以它为准；GlassCards 组件从这里取，保证像素一致。
  gradient:
    'linear-gradient(135deg, rgba(22,24,30,0.72), rgba(12,14,20,0.58))', // 暗玻璃卡斜向渐变
  strokeNormal: 'rgba(255,255,255,0.14)', // 普通项描边（实测 0.14）
  titleNormal: '#e8ecf2',                  // 普通项标题色（实测 #e8ecf2）
  strokeMuted: 'rgba(255,255,255,0.08)',  // 弱化项描边（line-through 反向项）
  titleMuted: '#7a818f',                   // 弱化项标题色（灰）
} as const;

/* ───────────────────── 全屏纹理（蓝图 §3.8；两条管线共用）─────────────────────
 * 全屏镜头（盖人像的过场/数据卡）用这套纹理铺底，避免纯平深底。
 */
export const texture = {
  gridLight: 'rgba(43,38,34,.05)',     // 浅底透视网格线
  gridDark: 'rgba(243,231,221,.05)',       // 深底透视网格线
  gridSize: 46,         // 网格格距(px)
  grainOpacity: 0.08, // 颗粒 overlay 不透明度
} as const;

/* focus 框三色（截图/画面同时标注多区域用；原硬编码于 ScreenshotScene/ShotRotateScene，2026-06-21 收口进 theme 单一真源，值未变）。 */
export const focusTones = {
  orange: { border: 'rgba(255,111,64,0.95)', fill: 'rgba(255,111,64,0.14)', label: '#ff6f40' },
  green: { border: 'rgba(61,220,132,0.95)', fill: 'rgba(61,220,132,0.15)', label: '#26b96b' },
  blue: { border: 'rgba(74,144,255,0.95)', fill: 'rgba(74,144,255,0.14)', label: '#367fe8' },
} as const;

/* 品牌色半透明调（镜头辉光 / 荧光笔扫亮底；= 品牌蓝 / 白 + 特定 alpha，原硬编码于 CTAScene/TransitionScene，2026-07-03 C5 收口进 theme 单一真源，值字节未变）。 */
export const tints = {
  blueGlow: 'rgba(61,133,232,0.16)',
  blueSweep: 'rgba(61,133,232,0.40)',
  whiteSweep: 'rgba(255,255,255,0.28)',
  orangeGlow: 'rgba(255,111,64,0.13)',
  orangeSweep: 'rgba(255,111,64,0.42)',
} as const;

export const theme = {
  colors, fonts, fontSize, spacing, radius, shadow, cards, motion, warmPaper, darkGlass, texture, focusTones, tints,
} as const;
export type Theme = typeof theme;
